name: noahkareus
favicon: null
layout_spectrum: 0.025355378165841103
typography_spectrum: 0.22117562405765057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.34973368141800165
  lightness: 0.687611251603812
  saturation: 0.027686068322509527
  rhythmicContrast: 0.281179953366518
purpose: []
