name: noahkareus
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22117562405765057
title: Noah Kareus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.687611251603812
  saturation: 1
  rhythmicContrast: 0.281179953366518
purpose: []
